### ISSUE TITLE
Why is this a separate library from M5StickC?

### ISSUE THREAD

**Issue by Gearme** [m5stack/M5StickC-Plus#11]
Given the similarities between the M5StickC and the M5StickC-Plus, it seems unnecessary to make this a completely separate library. There is already unnecessary divergence between the two libraries, e.g. the wake on motion functionality (present on M5StickC, missing here). With the platformio support already present, could we not just use build flags and platform settings to differentiate and otherwise use the same library for both?

**Comment by 1technophile** [comment]
It makes sense. Going further you could also propose a single library for all the M5 boards.

**Comment by Lukanite** [comment]
Agreed, looking for the ability to create a project with this board, and having the wake on motion capabilities; until then I'm stuck with just the older, non-plus units

**Comment by anuradhawick** [comment]
@Lukanite You mean this function `void enableWakeOnMotion(Ascale ascale, uint8_t thresh_num_lsb);` ? I am also waiting for things to be updated! Did you find any workaround?

**Comment by anuradhawick** [comment]
Thanks, that's seems to be a decent workaround. I did not know AXP class was changed too. Cheers!

**Comment by Tinyu-Zhao** [comment]
@anuradhawick @Lukanite @Gearme Add wake on motion function.
https://github.com/m5stack/M5StickC-Plus/commit/3ece12a8ae05c6d90756a9dec07134dbcbf9f075

If you want to use a unified API on almost all M5Stack host devices, we recommend using the [M5Unified](https://github.com/m5stack/M5Unified) library for development.
