### ISSUE TITLE
Cannot use M5.Lcd.setBrightness()

### ISSUE THREAD

**Issue by RuofengX** [m5stack/M5StickC-Plus#12]
Cannot use M5.Lcd.setBrightness(), vscode return ``undefined reference to `M5Display::setBrightness(unsigned char)'`` error.

**Comment by sburlot** [comment]
Don't know why, but the code for setBrightness in M5Display.c is in a "#if 0", so setBrightness isnt defined.

Use M5.Axp.ScreenBreath()

**Comment by RuofengX** [comment]
M5.Axp.ScreenBreath() works, thx!
