### ISSUE TITLE
Is someone going to update M5Stick+ on Arduino library manager?

### ISSUE THREAD

**Issue by Sarah-C** [m5stack/M5StickC-Plus#20]
The Arduino library manager says my Stick Plus is up to date on 0.0.2
But it's missing the entire directory: M5StickC-Plus/examples/Hat/C_BACK_DRIVER/
That folder's over 6 months old... so I figured there's probably several updates that should be in release 0.0.3 by now?

**Comment by Tinyu-Zhao** [comment]
[We have added him](https://github.com/m5stack/M5StickC-Plus/tree/master/examples/Hat/C_BACK_DRIVER)
