### ISSUE TITLE
Buzzer.update not in M5.update

### ISSUE THREAD

**Issue by lilalukas** [m5stack/M5StickC-Plus#3]
Please add the `M5.Beep.update()`-function to the `M5.update()`-function.
Otherwise the `M5.Beep.tome(FRQ, 200)` will not end after 200ms.

Thanks

**Comment by Sarah-C** [comment]
This has been added, and the issue should be closed.

M5StickC-Plus.cpp contains:

```
void M5StickCPlus::update() {
	M5.BtnA.read();
	M5.BtnB.read();
	M5.Beep.update();
}
```
