### ISSUE TITLE
The M5Display setBrightness(uint8_t brightness) method and others are disabled, why?

### ISSUE THREAD

**Issue by hpsaturn** [m5stack/M5StickC-Plus#30]
## Overview

Why is the reason of disabled this code: 

https://github.com/m5stack/M5StickC-Plus/blob/master/src/M5Display.cpp#L478-L884

Or, how to I can set the brightness on the M5StickC?

**Comment by Tinyu-Zhao** [comment]
`        M5.Axp.ScreenBreath(7);
`
