### ISSUE TITLE
Issues about led and ir transmitter

### ISSUE THREAD

**Issue by Krinou3000** [m5stack/M5StickC-Plus#32]
When I follow the tutorial to try uiflow to turn on the led, it's the ir transmitter that lights up. I see it while filming with my smartphone.

I reflashed the factorytest and the ir transmitter does not light up when I am on the ir test program.

could there be an address error for the LED and the ir transmitter?

**Comment by Tinyu-Zhao** [comment]
Hi @imliubo , please check this, thanks.

**Comment by Tinyu-Zhao** [comment]
Also, if you have more questions about UIFLOW, you can discuss and address them in our [official forum](https://community.m5stack.com)

**Comment by imliubo** [comment]
Hi @Krinou3000 ,
Can you provide some details? Such as code blocks.
