### ISSUE TITLE
ESP IDF mapping of screen PINs

### ISSUE THREAD

**Issue by mestefy** [m5stack/M5StickC-Plus#33]
Hello M5Stack team!

I was trying to run [this](https://github.com/espressif/esp-idf/tree/56659cdf36790e182451cd892ea349b29a27d333/examples/peripherals/lcd/tjpgd) ESP IDF sample on my new M5Stick C Plus. In order for it to work, I needed to map the sticks's PINs to the following:

EXAMPLE_PIN_NUM_PCLK | SCK
EXAMPLE_PIN_NUM_CS | CS
EXAMPLE_PIN_NUM_DC | DC
EXAMPLE_PIN_NUM_RST | RST
EXAMPLE_PIN_NUM_DATA0 | MOSI
EXAMPLE_PIN_NUM_BK_LIGHT | BCKL

I found most of the PIN numbers [here](https://github.com/m5stack/M5StickC-Plus/blob/master/src/utility/In_eSPI_Setup.h) however it seems that I am missing the `BCKL` PIN.
What PIN address does it have? Where can I find it? Will there other changes be needed in order for the sticks screen to work with ESP IDF?

Thank you!

**Comment by Tinyu-Zhao** [comment]
<img width="870" alt="image" src="https://github.com/m5stack/M5StickC-Plus/assets/44396641/bb63786a-24af-4936-9ded-48d5481edb09">
The backlight of the M5StickCPlus is output through the LDO2 of the AXP192, whose register address is 0x28.

AXP192 [datasheet](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/core/AXP192_datasheet_cn.pdf)
