### ISSUE TITLE
Esp-idf arduino component require

### ISSUE THREAD

**Issue by rafapaezbas** [m5stack/M5StickC-Plus#34]
https://github.com/m5stack/M5StickC-Plus/blob/3e9db294bac4cb99cdcf5353432df936619ad7b8/CMakeLists.txt#L13

Hello m5stack team,

this is more a question than an issue. Im trying to use M5StickC-Plus as a esp-idf component. Seems like it requires another component named arduino. What is the repo for the __arduino__ component?. I can only find this -> https://github.com/espressif/arduino-esp32

Is arduino-esp32 component compatible with M5SickC-Plus?

Thank you very much and kind regards,
Rafa

**Comment by alexeo** [comment]
I think you are right。

**Comment by alexeo** [comment]
https://www.youtube.com/watch?v=05GKbdcH92Y 可以参考这个

**Comment by ameerhazo** [comment]
Hello @rafapaezbas, are using PlatformIO to build this library?

**Comment by Tinyu-Zhao** [comment]
Recommended to use M5Unified, which is currently the main maintenance of both Arduino and ESP-IDF support library.
