### ISSUE TITLE
Free_Fonts.h missing

### ISSUE THREAD

**Issue by uehara00** [m5stack/M5StickC-Plus#38]
### Describe the bug

The source file "Free_Fonts.h" is missing.
So I cannot complete compiling codes with free font.
The statement below:
M5.Lcd.setFreeFont(FSS9);
causes a message:
error: 'struct GFXfont' has no member named 'range_num'

### To reproduce

#include <M5StickCPlus.h>
#include <Free_Fonts.h>
void setup()
{
  M5.begin();
  M5.Lcd.setFreeFont(FSS9);
  M5.Lcd.drawString("Test drawString", 0, 0, GFXFF);
}
void loop()
{
  M5.update();
}

### Expected behavior

I have copied "Free_Fonts.h" from M5Stack repository, and complete compiling and some free fonts are displayed on the LCD.

### Environment

- OS: Windows11
- IDE &IDE Version: 1.8.19
- Repository Version: 0.0.8

### Additional context

It will be same for the M5Stick repository.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC-Plus/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Thank you for your feedback, I have reproduced the problem and will add the missing files.
https://github.com/m5stack/M5StickC-Plus/commit/75db32f5bf1a6c835adef00b0457ac4441431bed
