### ISSUE TITLE
Cant Change CPU speed

### ISSUE THREAD

**Issue by Trickypos** [m5stack/M5StickC-Plus#39]
### Describe the bug

Micropython get an error when using machine.freq() to change CPU speed

### To reproduce

machine.freq(160000000)

### Expected behavior

No Error and cpu speed to change

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC-Plus/issues?q=)
- [X] My report contains all necessary details

**Comment by imliubo** [comment]
Hi @Trickypos ,
Sorry for this, after some investigation I found the reason, the "Power Management" was disable in UIFlow FW, but I don't know why, i will do some test. Maybe it will available on nexet verison.
```
# Power Management
CONFIG_PM_ENABLE=n
```
