### ISSUE TITLE
RTC.ccp has error: 2nd "GetDate(" needs changing to "SetDate("

### ISSUE THREAD

**Issue by Rob58329** [m5stack/M5StickC-Plus#41]
https://github.com/m5stack/M5StickC-Plus/blob/master/src/RTC.cpp as at 9Oct22 has an error in it:
* There are TWO "void RTC::GetDate(RTC_DateTypeDef* RTC_DateStruct)",
* the lower of which needs changing to "void RTC::SetDate(RTC_DateTypeDef* RTC_DateStruct)" 

Note that " Fixed Get/Set Data->Date #40 " does NOT appear to have fixed this error in RTC.ccp"...

**Comment by Tinyu-Zhao** [comment]
Fixed,0dc7e13
