### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by bierbarrel** [m5stack/M5StickC-Plus#44]
### Describe the bug

Just get a general error that says:

Error compiling for board M5Stick-C-plus. Just curious how to get around this error

Arduino: 1.8.16 (Windows 10), Board: "M5Stick-C-Plus, Default, 240MHz (WiFi/BT), 1500000, None, Disabled"

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

### To reproduce

just load and compile. I have loaded all libraries

### Expected behavior

I expect the program to compile and load

### Environment

- OS: Win 11
- IDE &IDE Version: arduino 1.8.16
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC-Plus/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Please attach this report so that you can better identify the problem
<img width="327" alt="image" src="https://user-images.githubusercontent.com/44396641/215375307-0c495a43-586d-44b0-91b1-f7e7997eea3d.png">

Also update the M5Stack board definition to version 2.0.6 and the M5StickCPlus library to version 0.0.8 and try again.

**Comment by bierbarrel** [comment]
All updated and here is what i get now:
 error: 'did' does not name a type; did you mean 'div'?
 Compilation error: 'struct i2s_pin_config_t' has no member named 'mck_io_num'; did you mean 'bck_io_num'?

**Comment by bierbarrel** [comment]
thx for the help

**Comment by Tinyu-Zhao** [comment]
> All updated and here is what i get now:
> 
>  error: 'did' does not name a type; did you mean 'div'?
> 
>  Compilation error: 'struct i2s_pin_config_t' has no member named 'mck_io_num'; did you mean 'bck_io_num'?

Please try to compile the sample program that comes with StickCPlus

**Comment by felmue** [comment]
Hi guys

maybe this will help. See [here](https://community.m5stack.com/topic/3959/m5stickc-or-m5stickc-plus-microphone-basic-example-not-working-solved/3).

Thanks
Felix

**Comment by bierbarrel** [comment]
I'm sorry. I don't have that code. I was trying to restore the StickCplus back to original configuration. Do you know where I can get a copy?

thx

**Comment by Tinyu-Zhao** [comment]
> I'm sorry. I don't have that code. I was trying to restore the StickCplus back to original configuration. Do you know where I can get a copy?
> 
> thx

Here, https://github.com/m5stack/M5StickC-Plus/tree/master/examples/Basics
