### ISSUE TITLE
How to use MPU6886

### ISSUE THREAD

**Issue by WebSamuraiDaisuke** [m5stack/M5StickC-Plus#5]
MPU6886 works in M5stickC by `M5.MPU6886.getAccelData(&accX, &accY, &accZ);`
So I write `M5.IMU.getAccelData(&accX, &accY, &accZ);`, but it get result "X is:0.00  Y is:0.00  Z is:0.00" in Plus.
How can I get values from MPU6866 in Plus?

**Comment by felmue** [comment]
Hello @WebSamuraiDaisuke 

Try calling `M5.IMU.Init();` before using the MPU6886.

Thanks
Felix

**Comment by Gitshaoxiang** [comment]
we already add an example.
