### ISSUE TITLE
After flash a .bin file with esptool.py, M5stickC Plus doesn't work

### ISSUE THREAD

**Issue by WebSamuraiDaisuke** [m5stack/M5StickC-Plus#9]
I inputed below:

`esptool.py --port COM4 -b 1500000 write_flash 0x00000 M5ZoomcontrollerPlus3.ino.m5stick_c.bin`

The M5stickC Plus doesn't work after this command. I think something wrong with this command.
Because of hiding my code, I need this process. Please kindly give me advice.

Best regards

**Comment by Tinyu-Zhao** [comment]
Reference examples

Auto-burn

`esptool.py -b 1500000 write_flash 0 dump.bin`

Automatically read

`esptool.py -b 1500000 read_flash 0 0x400000 dump.bin`

Specify serial port `USB1` baud rate `460800` Read 1MB from 0x10000 address to dump.bin file

esptool.py -p /dev/ttyUSB1 -b 460800 read_flash 0x10000 0x100000 dump.bin
